# AUTOGENERATED FROM 'usal/infrastructure/queries/author/list_authors.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class ListAuthorsResult(NoPydanticValidation):
    id: uuid.UUID
    full_name: str
    pp_url: str | None


async def list_authors(
    executor: gel.AsyncIOExecutor,
    *,
    search: str | None = None,
    offset: int | None = None,
    limit: int | None = None,
) -> list[ListAuthorsResult]:
    return await executor.query(
        """\
        WITH
            search := <optional str>$search,

        FILTERED_AUTHOR := (
            SELECT Author
            FILTER (
            (.full_name ILIKE '%' ++ search ++ '%' IF EXISTS search ELSE TRUE)
            )
            ORDER BY .full_name ASC
            OFFSET <optional int64>$offset
            LIMIT <optional int64>$limit
        )
        SELECT FILTERED_AUTHOR {
            id,
            full_name,
            pp_url
        }\
        """,
        search=search,
        offset=offset,
        limit=limit,
    )
