# AUTOGENERATED FROM 'usal/infrastructure/queries/otp/get_otp_by_id.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema

        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetOtpByIdResult(NoPydanticValidation):
    id: uuid.UUID
    user_id: uuid.UUID | None
    secret: str
    expiration_time: datetime.datetime


async def get_otp_by_id(
    executor: gel.AsyncIOExecutor,
    *,
    verification_id: uuid.UUID,
) -> GetOtpByIdResult | None:
    return await executor.query_single(
        """\
        SELECT OTP {
            id,
            user_id := .user.id,
            secret,
            expiration_time
        }
        FILTER .id = <uuid>$verification_id\
        """,
        verification_id=verification_id,
    )
