# AUTOGENERATED FROM 'usal/infrastructure/queries/qa/get_qa_by_id.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema

        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetQaByIdResult(NoPydanticValidation):
    id: uuid.UUID
    answer: str


async def get_qa_by_id(
    executor: gel.AsyncIOExecutor,
    *,
    qa_id: uuid.UUID,
) -> GetQaByIdResult | None:
    return await executor.query_single(
        """\
        SELECT QASection {
            id,
            answer,
        }
        FILTER .id = <uuid>$qa_id\
        """,
        qa_id=qa_id,
    )
