# AUTOGENERATED FROM 'usal/infrastructure/queries/qa/list_user_qa.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class ListUserQaResult(NoPydanticValidation):
    id: uuid.UUID
    question: str


class QAType(enum.Enum):
    UNIVERSITY = "UNIVERSITY"
    ACADEMIC = "ACADEMIC"
    FINANCIAL = "FINANCIAL"
    PERSONAL = "PERSONAL"
    GRADUATE = "GRADUATE"
    POST_GRADUATE = "POST_GRADUATE"
    PHD = "PHD"
    FAMILY = "FAMILY"


async def list_user_qa(
    executor: gel.AsyncIOExecutor,
    *,
    question: str | None = None,
    type: QAType,
    offset: int | None = None,
    limit: int | None = None,
) -> list[ListUserQaResult]:
    return await executor.query(
        """\
        WITH
            question := <optional str>$question,
            qa_type:= <QAType>$type,

        FILTERED_QA := (
            SELECT QASection
            FILTER (
            (.question ILIKE '%' ++ question ++ '%' IF EXISTS question ELSE TRUE)
            )
            AND .type = qa_type
            AND .status = QAStatus.ACTIVE
            ORDER BY .question ASC
            OFFSET <optional int64>$offset
            LIMIT <optional int64>$limit
        )
        SELECT FILTERED_QA {
            id,
            question,
        }\
        """,
        question=question,
        type=type,
        offset=offset,
        limit=limit,
    )
