# AUTOGENERATED FROM 'usal/infrastructure/queries/admin/get_admin_by_username.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema

        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetAdminByUsernameResult(NoPydanticValidation):
    id: uuid.UUID
    username: str
    email: str
    password: str


async def get_admin_by_username(
    executor: gel.AsyncIOExecutor,
    *,
    username: str,
) -> GetAdminByUsernameResult | None:
    return await executor.query_single(
        """\
        SELECT Admin {
          id,
          username,
          email,
          password:= .password_hash
        }
        FILTER .username = <str>$username
        LIMIT 1;\
        """,
        username=username,
    )
