# AUTOGENERATED FROM 'usal/infrastructure/queries/user/user_exists.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import gel


async def user_exists(
    executor: gel.AsyncIOExecutor,
    *,
    email: str,
) -> bool:
    return await executor.query_single(
        """\
        SELECT EXISTS (
            SELECT User 
            FILTER .email = <str>$email and .status != UserStatus.INACTIVE and .status != UserStatus.DELETED
        )\
        """,
        email=email,
    )
