# AUTOGENERATED FROM 'usal/infrastructure/queries/resources/list_resources.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class ListResourcesResult(NoPydanticValidation):
    id: uuid.UUID
    title: str
    image: str
    description: str
    file: str


async def list_resources(
    executor: gel.AsyncIOExecutor,
) -> list[ListResourcesResult]:
    return await executor.query(
        """\
        SELECT Resources {
            id,
            title,
            image,
            description,
            file
        }\
        """,
    )
