# AUTOGENERATED FROM 'usal/infrastructure/queries/university/increase_view_count.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class IncreaseViewCountResult(NoPydanticValidation):
    id: uuid.UUID


async def increase_view_count(
    executor: gel.AsyncIOExecutor,
    *,
    university_id: uuid.UUID,
) -> IncreaseViewCountResult | None:
    return await executor.query_single(
        """\
        UPDATE University
        FILTER .id = <uuid>$university_id
        SET {
          view_count := .view_count + 1,
        }\
        """,
        university_id=university_id,
    )
