# AUTOGENERATED FROM 'usal/infrastructure/queries/university/list_degrees.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class DegreeNames(enum.Enum):
    ASSOCIATES_DEGREE = "ASSOCIATES_DEGREE"
    BACHELORS_DEGREE = "BACHELORS_DEGREE"
    MASTERS_DEGREE = "MASTERS_DEGREE"
    DOCTORAL_DEGREE = "DOCTORAL_DEGREE"


@dataclasses.dataclass
class ListDegreesResult(NoPydanticValidation):
    id: uuid.UUID
    name: DegreeNames


async def list_degrees(
    executor: gel.AsyncIOExecutor,
) -> list[ListDegreesResult]:
    return await executor.query(
        """\
        SELECT Degree {
            id,
            name,
        }\
        """,
    )
