from enum import Enum


class AdminPermissions(Enum):
    """
    Enum for admin permissions.
    """

    ARTICLE_MANAGEMENT = "ARTICLE_MANAGEMENT"
    UNIVERSITY_MANAGEMENT = "UNIVERSITY_MANAGEMENT"
    QA_MANAGEMENT = "QA_MANAGEMENT"
    RESOURCES_MANAGEMENT = "RESOURCES_MANAGEMENT"
    NOTIFICATION_MANAGEMENT = "NOTIFICATION_MANAGEMENT"
    USER_MANAGEMENT = "USER_MANAGEMENT"
    MARKETING_MANAGEMENT = "MARKETING_MANAGEMENT"
